import React, { useState, useEffect, useCallback } from 'react';
import { Star, Quote, ChevronLeft, ChevronRight } from 'lucide-react';

const testimonials = [
  {
    name: "Dr. Sarah Johnson",
    role: "Principal, Delhi Public School",
    image: "https://images.unsplash.com/photo-1494790108377-be9c29b29330?auto=format&fit=crop&w=200&h=200",
    content: "Inkredible has transformed how we create and manage our assessments. The AI-powered system saves hours of work while maintaining high standards.",
    rating: 5
  },
  {
    name: "Prof. Rajesh Kumar",
    role: "Head of Mathematics, IIT Coaching Center",
    image: "https://images.unsplash.com/photo-1472099645785-5658abf4ff4e?auto=format&fit=crop&w=200&h=200",
    content: "The question variety and difficulty balancing is exceptional. It's like having an expert paper setter available 24/7.",
    rating: 5
  },
  {
    name: "Ms. Priya Sharma",
    role: "Academic Director, Learning Excellence",
    image: "https://images.unsplash.com/photo-1438761681033-6461ffad8d80?auto=format&fit=crop&w=200&h=200",
    content: "Our students' performance analytics have never been clearer. The insights we get help us adapt our teaching methods effectively.",
    rating: 5
  },
  {
    name: "Dr. Amit Patel",
    role: "Director, Career Point Institute",
    image: "https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?auto=format&fit=crop&w=200&h=200",
    content: "The AI-generated questions are on par with actual competitive exams. It's an invaluable tool for our JEE and NEET preparation programs.",
    rating: 5
  },
  {
    name: "Mrs. Anjali Desai",
    role: "Vice Principal, Modern School",
    image: "https://images.unsplash.com/photo-1544005313-94ddf0286df2?auto=format&fit=crop&w=200&h=200",
    content: "The automated evaluation feature has reduced our teachers' workload significantly. Now they can focus more on teaching and less on grading.",
    rating: 5
  },
  {
    name: "Dr. Michael Chang",
    role: "Education Technology Consultant",
    image: "https://images.unsplash.com/photo-1506794778202-cad84cf45f1d?auto=format&fit=crop&w=200&h=200",
    content: "I've implemented Inkredible in several institutions, and the results have been consistently impressive. The platform's adaptability is remarkable.",
    rating: 5
  },
  {
    name: "Prof. Sunita Rao",
    role: "HOD Science Department, Delhi International School",
    image: "https://images.unsplash.com/photo-1531123897727-8f129e1688ce?auto=format&fit=crop&w=200&h=200",
    content: "The quality of science questions generated by Inkredible is exceptional. It perfectly aligns with various board examination patterns.",
    rating: 5
  }
];

export default function Testimonials() {
  const [currentIndex, setCurrentIndex] = useState(0);
  const [isAnimating, setIsAnimating] = useState(false);
  const [isMobile, setIsMobile] = useState(false);

  useEffect(() => {
    const checkMobile = () => {
      setIsMobile(window.innerWidth < 768);
    };
    
    checkMobile();
    window.addEventListener('resize', checkMobile);
    return () => window.removeEventListener('resize', checkMobile);
  }, []);

  const itemsPerView = isMobile ? 1 : window.innerWidth < 1024 ? 2 : 3;
  const maxIndex = testimonials.length - itemsPerView;

  const showPrev = useCallback(() => {
    if (!isAnimating) {
      setIsAnimating(true);
      setCurrentIndex((prev) => (prev === 0 ? maxIndex : prev - 1));
      setTimeout(() => setIsAnimating(false), 500);
    }
  }, [isAnimating, maxIndex]);

  const showNext = useCallback(() => {
    if (!isAnimating) {
      setIsAnimating(true);
      setCurrentIndex((prev) => (prev === maxIndex ? 0 : prev + 1));
      setTimeout(() => setIsAnimating(false), 500);
    }
  }, [isAnimating, maxIndex]);

  useEffect(() => {
    const timer = setInterval(showNext, 5000);
    return () => clearInterval(timer);
  }, [currentIndex, showNext]);

  return (
    <div className="relative px-4 sm:px-6 lg:px-8 py-16 sm:py-24">
      {/* Background Elements */}
      <div className="absolute inset-0 bg-gradient-to-b from-transparent via-purple-500/5 to-transparent" />
      <div className="absolute top-10 left-10 w-36 sm:w-72 h-36 sm:h-72 bg-purple-500/30 rounded-full filter blur-3xl opacity-20" />
      <div className="absolute bottom-10 right-10 w-36 sm:w-72 h-36 sm:h-72 bg-blue-500/30 rounded-full filter blur-3xl opacity-20" />

      <div className="relative">
        <div className="text-center mb-8 sm:mb-16">
          <p className="text-sm sm:text-base mb-2 dark:text-gray-400 text-gray-600">
            Made for Schools & Students
          </p>
          <h2 className="text-3xl sm:text-4xl font-bold mb-3 sm:mb-4">
            <span className="bg-gradient-to-r from-purple-400 to-blue-400 text-transparent bg-clip-text dark:from-purple-400 dark:to-blue-400 from-purple-600 to-blue-600">
              What Our Users Say
            </span>
          </h2>
          <p className="dark:text-gray-400 text-gray-600 max-w-2xl mx-auto text-sm sm:text-base">
            Join thousands of satisfied educators who have transformed their assessment process with Inkredible.
          </p>
        </div>

        <div className="relative">
          {/* Navigation Buttons */}
          <button
            onClick={showPrev}
            className="absolute left-0 top-1/2 -translate-y-1/2 -translate-x-2 sm:-translate-x-12 z-10 bg-purple-500/10 hover:bg-purple-500/20 p-2 rounded-full transition-all duration-300"
            aria-label="Previous testimonial"
          >
            <ChevronLeft className="w-5 h-5 sm:w-6 sm:h-6 text-purple-400" />
          </button>
          <button
            onClick={showNext}
            className="absolute right-0 top-1/2 -translate-y-1/2 translate-x-2 sm:translate-x-12 z-10 bg-purple-500/10 hover:bg-purple-500/20 p-2 rounded-full transition-all duration-300"
            aria-label="Next testimonial"
          >
            <ChevronRight className="w-5 h-5 sm:w-6 sm:h-6 text-purple-400" />
          </button>

          {/* Testimonials Carousel */}
          <div className="overflow-hidden">
            <div
              className="flex transition-transform duration-500 ease-in-out"
              style={{
                transform: `translateX(-${currentIndex * (100 / itemsPerView)}%)`,
              }}
            >
              {testimonials.map((testimonial, index) => (
                <div
                  key={index}
                  className={`${
                    isMobile ? 'w-full' : 'w-1/2 lg:w-1/3'
                  } flex-shrink-0 px-2 sm:px-4`}
                >
                  <div className="relative bg-white/90 dark:bg-gray-800/50 backdrop-blur-sm p-4 sm:p-6 rounded-2xl border border-purple-500/20 hover:border-purple-500/40 transition-all duration-300 h-full">
                    {/* Quote Icon */}
                    <div className="absolute -top-3 -left-3 sm:-top-4 sm:-left-4">
                      <div className="bg-gradient-to-br from-purple-500 to-blue-500 w-6 h-6 sm:w-8 sm:h-8 rounded-full flex items-center justify-center">
                        <Quote className="w-3 h-3 sm:w-4 sm:h-4 text-white" />
                      </div>
                    </div>

                    <div className="mb-4 sm:mb-6">
                      {/* Rating */}
                      <div className="flex gap-1 mb-3 sm:mb-4">
                        {[...Array(testimonial.rating)].map((_, i) => (
                          <Star key={i} className="w-4 h-4 sm:w-5 sm:h-5 fill-purple-500 text-purple-500" />
                        ))}
                      </div>
                      {/* Content */}
                      <p className="dark:text-gray-300 text-gray-700 italic text-sm sm:text-base">"{testimonial.content}"</p>
                    </div>

                    {/* Author */}
                    <div className="flex items-center gap-3 sm:gap-4">
                      <img
                        src={testimonial.image}
                        alt={testimonial.name}
                        className="w-10 h-10 sm:w-12 sm:h-12 rounded-full object-cover border-2 border-purple-500/50"
                      />
                      <div>
                        <h4 className="font-semibold dark:text-purple-400 text-purple-600 text-sm sm:text-base">{testimonial.name}</h4>
                        <p className="text-xs sm:text-sm dark:text-gray-400 text-gray-600">{testimonial.role}</p>
                      </div>
                    </div>
                  </div>
                </div>
              ))}
            </div>
          </div>
        </div>
      </div>
    </div>
  );
}
